### ISSUE TITLE
Use real screenshots on landing page

### ISSUE THREAD

**Issue by leonoverweel** [atlarge-research/opendc-frontend#12]
Use [real screenshots](https://github.com/atlarge-research/opendc/tree/master/images) on the landing page instead of the mockups we have now.

**Comment by gandreadis** [comment]
I'm not yet entirely sure how I want to approach this. I think having exact duplicates of those image files in both the main OpenDC and frontend repo would be less than ideal. Maybe we could move those screenshots of the main repo over to the frontend repo, since they are more relevant to it? The links on the main OpenDC repo documentation could be updated to link to this sub-repo. 
@leonoverweel, any thoughts/ideas?

**Comment by leonoverweel** [comment]
I think just using the versions hosted on the `opendc` repo is fine for now. If it turns out the CDN is too slow, we can look at other options.
