### ISSUE TITLE
Experiment names can execute arbitrary javascript code

### ISSUE THREAD

**Issue by daniel-vos** [atlarge-research/opendc-frontend#15]
If a user inserts javascript code such as `<script>alert("Hello")</script>` as experiment name, then this code gets executed the next time an experiment is ran.

**Comment by leonoverweel** [comment]
Thanks Daniël. Please take a look at this @gandreadis -- this could be exploited to allow an attacker to get to arbitrary other users' data by inserting such code in a shared `Project`.

**Comment by gandreadis** [comment]
I've let jQuery do the actual work of escaping all text input that is sent to the server. To complete the protection against this attack vector, however, we also need to implement this on the server-side (see [this issue on the web-server repo](https://github.com/atlarge-research/opendc-web-server/issues/5)), so that people using the API can't exploit it in this way, either. (cc @leonoverweel)
