### ISSUE TITLE
Grid disappears after clicking on oddly located room

### ISSUE THREAD

**Issue by daniel-vos** [atlarge-research/opendc-frontend#19]
After clicking inside a room all the way in the bottom-right corner, then clicking out of the room again, the grid seems to disappear. Reloading the page does not fix it.

**Comment by gandreadis** [comment]
Interesting :) Probably due to the zooming algorithm trying to fit all rooms on the same screen (and failing).
Thanks @daniel-vos for reporting this! I'll have a look into the precise cause of this ASAP.

**Comment by gandreadis** [comment]
With the port to React.js, I think that this issue is not relevant anymore, as I've changed the UX in some ways in the process. Most notably, the zoom now doesn't change anymore when you click on a room, so any zooming issues can only happen at the very beginning (at load-time), or when you resize your browser window. In any case, not when you click on a room.

Nevertheless, thanks for having reported this, please don't hesitate to file any other issues when you encounter them 🙂
